package importantnote;

public class NOTESANDKEYPOINTS {

}


// -------> 1)THIS KEYWORD IS USED AS  REFERENCE  VARAIBALE TO REFER TO THE CURRENT OBJECT 

//--------> 2)WHEN THE INSTANCE VARAIBALE AND LOCAL PARAMETER ARE HAVING THE SAME NAME AND JAVA CANNTO DISTNGIUSH BETWEEEN BOTJ

//----------> 3) ** SO IF U DIRECTLY USE THE PARAMETER IT WILL BE CONSIDER AS LOCAL PARAMETER IF U REFER  IT WITH THIS 
//				3.2)    (THIS.PROPERTY ) THEN IT WILL REFER TO THE INSTACE VARAIBALE

//
//----------> TO AVOID THE 
//
//
//
//
//---> this must be the first statement inside a  constructor
